// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvheOTzNZETOMgcm4T1fkHygEQ0fdA5_Q',
    appId: '1:755114408441:web:a685a79c8429b6547ea528',
    messagingSenderId: '755114408441',
    projectId: 'addfirebase-492a3',
    authDomain: 'addfirebase-492a3.firebaseapp.com',
    storageBucket: 'addfirebase-492a3.appspot.com',
    measurementId: 'G-YSJD0C1SGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9l-cf5AE7JbFwmtJGa_bQT3pEAyK9GM',
    appId: '1:755114408441:android:9360ec632c55d1b57ea528',
    messagingSenderId: '755114408441',
    projectId: 'addfirebase-492a3',
    storageBucket: 'addfirebase-492a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOijhXd7_iZ_3J6vMv6b-IL2ZjUc4fLC4',
    appId: '1:755114408441:ios:e099a0220a8d7d757ea528',
    messagingSenderId: '755114408441',
    projectId: 'addfirebase-492a3',
    storageBucket: 'addfirebase-492a3.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOijhXd7_iZ_3J6vMv6b-IL2ZjUc4fLC4',
    appId: '1:755114408441:ios:e099a0220a8d7d757ea528',
    messagingSenderId: '755114408441',
    projectId: 'addfirebase-492a3',
    storageBucket: 'addfirebase-492a3.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvheOTzNZETOMgcm4T1fkHygEQ0fdA5_Q',
    appId: '1:755114408441:web:aef32800d758f2d07ea528',
    messagingSenderId: '755114408441',
    projectId: 'addfirebase-492a3',
    authDomain: 'addfirebase-492a3.firebaseapp.com',
    storageBucket: 'addfirebase-492a3.appspot.com',
    measurementId: 'G-CX26WKVSFV',
  );
}
